package app.lasco.importer.ffi

import app.lasco.importer.model.ImportedMedia
import app.lasco.importer.model.RemoteBenchmark
import app.lasco.importer.model.SourceMetadata
import java.nio.file.Path
import uniffi.lasco_ffi.FfiLibrary
import uniffi.lasco_ffi.FfiAlbumUuid
import uniffi.lasco_ffi.FfiMediaImportMetadata
import uniffi.lasco_ffi.FfiMediaUuid
import uniffi.lasco_ffi.FfiRemoteUuid
import uniffi.lasco_ffi.PushProgressSink

/**
 * Thin adapter over code generated by `lasco-ffi`. No Rust service is introduced: imports,
 * albums, pushes, and eviction all call the existing FFI object.
 */
class UniffiLascoGateway(
    private val library: FfiLibrary,
    private val appSupportDirectory: String,
) : LascoGateway {
    override fun remotes() = library.listRemotes().map { LascoRemote(it.remoteId.value, it.name, it.kind) }

    override fun createAlbum(name: String): String = library.createAlbum(name, null).value
    override fun addMediaToAlbum(albumId: String, mediaId: String) = library.addMediaToAlbum(FfiAlbumUuid(albumId), FfiMediaUuid(mediaId))

    override fun importMedia(path: Path, metadata: SourceMetadata, aaeMediaId: String?, liveVideoMediaId: String?): ImportedMedia {
        val result = library.importMediaWithMetadata(
            path.toString(), null,
            FfiMediaImportMetadata(metadata.originalFilename, metadata.capturedAt, metadata.modifiedAt,
                metadata.latitude, metadata.longitude, aaeMediaId?.let(::FfiMediaUuid), liveVideoMediaId?.let(::FfiMediaUuid)),
        )
        return ImportedMedia(result.mediaId.value, result.alreadyExisted)
    }

    override suspend fun benchmark(remote: LascoRemote, bytesPerUpload: Long): RemoteBenchmark {
        val samples = library.benchmarkRemoteUploadAsync(FfiRemoteUuid(remote.id), appSupportDirectory, bytesPerUpload.toULong(), 5u)
        val best = samples.maxBy { it.bytesPerSecond }
        return RemoteBenchmark(remote.id, remote.name, best.parallelUploads.toInt(), best.bytesPerSecond.toLong())
    }

    override suspend fun push(remote: LascoRemote, maxConcurrentMediaUploads: Int, onProgress: (Double) -> Unit) {
        library.pushRemoteUsingConfiguredMediaSourcesWithOptionsAsync(
            FfiRemoteUuid(remote.id), appSupportDirectory,
            object : PushProgressSink { override fun uploadProgress(fraction: Double) = onProgress(fraction) },
            maxConcurrentMediaUploads.toUByte(),
        )
    }

    override fun evict(mediaIds: List<String>) = library.evictLocalData(mediaIds.map(::FfiMediaUuid))
    override fun close() = library.close()
}
