package app.lasco.importer.ffi

import app.lasco.importer.model.ImportedMedia
import app.lasco.importer.model.ApplePhotosAssetRevision
import app.lasco.importer.model.ApplePhotosCollectionDescriptor
import app.lasco.importer.model.ApplePhotosCollectionKind
import app.lasco.importer.model.ApplePhotosResourceDescriptor
import app.lasco.importer.model.ApplePhotosResourceType
import app.lasco.importer.model.RemoteBenchmark
import app.lasco.importer.model.SourceMetadata
import java.nio.file.Path
import uniffi.lasco_ffi.FfiLibrary
import uniffi.lasco_ffi.FfiAlbumUuid
import uniffi.lasco_ffi.FfiMediaImportMetadata
import uniffi.lasco_ffi.FfiMediaUuid
import uniffi.lasco_ffi.FfiApplePhotosAssetRevision
import uniffi.lasco_ffi.FfiApplePhotosResourceDescriptor
import uniffi.lasco_ffi.FfiApplePhotosResourceOrigin
import uniffi.lasco_ffi.FfiApplePhotosResourceType
import uniffi.lasco_ffi.FfiApplePhotosCollectionIdentity
import uniffi.lasco_ffi.FfiApplePhotosCollectionLink
import uniffi.lasco_ffi.FfiApplePhotosCollectionKind
import uniffi.lasco_ffi.FfiRemoteUuid
import uniffi.lasco_ffi.PushProgressSink

/**
 * Thin adapter over code generated by `lasco-ffi`. No Rust service is introduced: imports,
 * albums, and pushes all call the existing FFI object.
 */
class UniffiLascoGateway(
    private val library: FfiLibrary,
    private val appSupportDirectory: String,
) : LascoGateway {
    internal fun ffiLibrary(): FfiLibrary = library
    override val libraryId: String get() = library.libraryId().value

    override fun remotes() = library.listRemotes().map { LascoRemote(it.remoteId.value, it.name, it.kind) }

    override fun createAlbum(name: String, parentAlbumId: String?): String = library.createAlbum(name, parentAlbumId?.let(::FfiAlbumUuid)).value
    override fun addMediaToAlbum(albumId: String, mediaId: String) = library.addMediaToAlbum(FfiAlbumUuid(albumId), FfiMediaUuid(mediaId))

    override fun importMedia(path: Path, metadata: SourceMetadata, aaeMediaId: String?, liveVideoMediaId: String?): ImportedMedia {
        val result = library.importMediaWithMetadata(
            path.toString(), null,
            FfiMediaImportMetadata(metadata.originalFilename, metadata.capturedAt, metadata.modifiedAt,
                metadata.latitude, metadata.longitude, aaeMediaId?.let(::FfiMediaUuid), liveVideoMediaId?.let(::FfiMediaUuid)),
        )
        return ImportedMedia(result.mediaId.value, result.alreadyExisted)
    }

    override fun setMediaThumbnail(mediaId: String, data: ByteArray) {
        library.setMediaThumbnail(FfiMediaUuid(mediaId), data)
    }

    override fun applePhotosAssetRevisionMediaIds(revision: ApplePhotosAssetRevision): Map<ApplePhotosResourceDescriptor, String>? {
        val cloudAssetId = revision.cloudAssetId ?: return null
        val resources = revision.resources.map { FfiApplePhotosResourceDescriptor(it.type.toFfi(), it.filename) }
        val mediaIds = library.applePhotosAssetRevisionMediaIds(
            FfiApplePhotosAssetRevision(cloudAssetId, revision.modificationDate, resources),
        ) ?: return null
        return revision.resources.zip(mediaIds).associate { (descriptor, mediaId) -> descriptor to mediaId.value }
    }

    override fun recordApplePhotosResourceOrigin(mediaId: String, revision: ApplePhotosAssetRevision, resourceType: ApplePhotosResourceType, filename: String) {
        val cloudAssetId = revision.cloudAssetId ?: return
        library.recordApplePhotosResourceOrigin(
            FfiApplePhotosResourceOrigin(FfiMediaUuid(mediaId), cloudAssetId, revision.modificationDate, resourceType.toFfi(), filename),
        )
    }

    override fun applePhotosCollectionLinks(collections: List<ApplePhotosCollectionDescriptor>): List<String?> =
        library.applePhotosCollectionLinks(collections.map {
            FfiApplePhotosCollectionIdentity(it.cloudCollectionId, it.kind.toFfiCollectionKind())
        }).map { it?.value }

    override fun mediaAlbumIds(mediaId: String): Set<String> =
        library.mediaAlbumIds(FfiMediaUuid(mediaId)).mapTo(mutableSetOf()) { it.value }

    override fun recordApplePhotosCollectionLink(albumId: String, collection: ApplePhotosCollectionDescriptor) {
        library.recordApplePhotosCollectionLink(
            FfiApplePhotosCollectionLink(FfiAlbumUuid(albumId), collection.cloudCollectionId, collection.kind.toFfiCollectionKind()),
        )
    }

    override suspend fun fetchRemoteOperations(remote: LascoRemote) {
        library.fetchRemoteAsync(FfiRemoteUuid(remote.id), appSupportDirectory)
    }

    override fun hasUnpushedOperations(remote: LascoRemote): Boolean =
        library.hasUnpushedChanges(FfiRemoteUuid(remote.id))

    override suspend fun confirmRemoteMedia(remote: LascoRemote) {
        library.confirmRemoteMediaAsync(FfiRemoteUuid(remote.id), appSupportDirectory)
    }

    override fun confirmedRemoteMediaIds(remote: LascoRemote, mediaIds: Set<String>): Set<String> =
        library.confirmedRemoteMediaIds(
            FfiRemoteUuid(remote.id),
            mediaIds.map(::FfiMediaUuid),
        ).mapTo(mutableSetOf()) { it.value }

    override suspend fun benchmark(remote: LascoRemote, bytesPerUpload: Long): RemoteBenchmark {
        // Do not spend extra data on parallel tests when one stream cannot sustain 1 MiB/s.
        // The serial sample is also the selected setting in that case.
        val single = library.benchmarkRemoteUploadAsync(
            FfiRemoteUuid(remote.id), appSupportDirectory, bytesPerUpload.toULong(), 1u,
        ).single()
        if (shouldRestrictToOneUpload(single.bytesPerSecond.toLong())) {
            return RemoteBenchmark(remote.id, remote.name, 1, single.bytesPerSecond.toLong())
        }
        // Four uploads per remote is the highest useful setting for the desktop importer.
        val samples = library.benchmarkRemoteUploadAsync(FfiRemoteUuid(remote.id), appSupportDirectory, bytesPerUpload.toULong(), 4u)
        val best = samples.maxBy { it.bytesPerSecond }
        return RemoteBenchmark(remote.id, remote.name, best.parallelUploads.toInt(), best.bytesPerSecond.toLong())
    }

    override suspend fun push(remote: LascoRemote, maxConcurrentMediaUploads: Int, onProgress: (Double) -> Unit) {
        library.pushRemoteUsingConfiguredMediaSourcesWithOptionsAsync(
            FfiRemoteUuid(remote.id), appSupportDirectory,
            object : PushProgressSink { override fun uploadProgress(fraction: Double) = onProgress(fraction) },
            maxConcurrentMediaUploads.toUByte(),
        )
    }

    override fun close() = library.close()
}

/** 1 MiB/s, matching the binary MB units used in the desktop importer UI. */
internal const val MINIMUM_SPEED_FOR_PARALLEL_UPLOADS = 1024L * 1024L

internal fun shouldRestrictToOneUpload(bytesPerSecond: Long): Boolean =
    bytesPerSecond < MINIMUM_SPEED_FOR_PARALLEL_UPLOADS

private fun ApplePhotosResourceType.toFfi(): FfiApplePhotosResourceType = when (this) {
    ApplePhotosResourceType.PHOTO -> FfiApplePhotosResourceType.PHOTO
    ApplePhotosResourceType.FULL_SIZE_PHOTO -> FfiApplePhotosResourceType.FULL_SIZE_PHOTO
    ApplePhotosResourceType.VIDEO -> FfiApplePhotosResourceType.VIDEO
    ApplePhotosResourceType.FULL_SIZE_VIDEO -> FfiApplePhotosResourceType.FULL_SIZE_VIDEO
    ApplePhotosResourceType.ADJUSTMENT_DATA -> FfiApplePhotosResourceType.ADJUSTMENT_DATA
    ApplePhotosResourceType.PAIRED_VIDEO -> FfiApplePhotosResourceType.PAIRED_VIDEO
    ApplePhotosResourceType.FULL_SIZE_PAIRED_VIDEO -> FfiApplePhotosResourceType.FULL_SIZE_PAIRED_VIDEO
}

private fun ApplePhotosCollectionKind.toFfiCollectionKind(): FfiApplePhotosCollectionKind = when (this) {
    ApplePhotosCollectionKind.FOLDER -> FfiApplePhotosCollectionKind.FOLDER
    ApplePhotosCollectionKind.ALBUM -> FfiApplePhotosCollectionKind.ALBUM
}
